[package]
name = "rustsynth"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.2"
anyhow = "1.0"
eframe = "0.22.0"
crossterm = "0.25"
parking_lot = "0.12.1"
dasp_sample = "0.11"
egui = "0.21.0"
rand = "0.8.5"