name: Cross-Compile

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    # "fail-fast: false" so if one target fails, the others still build.
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux (cross)
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use_cross: true
            artifact_suffix: "linux_x86_64_gnu"
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            use_cross: true
            artifact_suffix: "linux_x86_64_musl"
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            use_cross: true
            artifact_suffix: "linux_aarch64"
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            use_cross: true
            artifact_suffix: "linux_i686"

          # macOS (native Cargo)
          - os: macos-latest
            target: x86_64-apple-darwin
            use_cross: false
            artifact_suffix: "macOS_x86_64"
          - os: macos-latest
            target: aarch64-apple-darwin
            use_cross: false
            artifact_suffix: "macOS_arm64"

          # Windows (native Cargo)
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            use_cross: false
            artifact_suffix: "windows_x86_64_gnu"
          - os: windows-latest
            target: i686-pc-windows-gnu
            use_cross: false
            artifact_suffix: "windows_i686_gnu"

    runs-on: ${{ matrix.os }}

    steps:
      # 1) Check out your Rust project
      - name: Check out source
        uses: actions/checkout@v4

      # 2) Create a Cross.toml on the fly if "use_cross" is true
      #    so we can install ALSA dev libs inside cross's Docker images.
      - name: Create Cross.toml (for ALSA)
        if: ${{ matrix.use_cross }}
        run: |
          cat <<EOF > Cross.toml
          [target.x86_64-unknown-linux-gnu]
          pre-build = [
            "apt-get update && apt-get install -y libasound2-dev"
          ]

          [target.x86_64-unknown-linux-musl]
          pre-build = [
            "apt-get update && apt-get install -y libasound2-dev"
          ]

          [target.aarch64-unknown-linux-gnu]
          pre-build = [
            "apt-get update && apt-get install -y libasound2-dev"
          ]

          [target.i686-unknown-linux-gnu]
          pre-build = [
            "apt-get update && apt-get install -y libasound2-dev"
          ]
          EOF

      # 3) Install the Rust toolchain + the needed target
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      # 4) Install cross (only if "use_cross" is true)
      - name: Install cross
        if: ${{ matrix.use_cross }}
        run: cargo install cross --git https://github.com/cross-rs/cross

      # 5) Build your binary
      - name: Build
        run: |
          if [ "${{ matrix.use_cross }}" = "true" ]; then
            cross build --release --target ${{ matrix.target }} --bin RustWave
          else
            cargo build --release --target ${{ matrix.target }} --bin RustWave
          fi

      # 6) Copy the artifact to a friendly name
      - name: Stage artifact
        run: |
          BIN_NAME="RustWave"
          SUFFIX=""
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            SUFFIX=".exe"
          fi

          ARTIFACT="target/${{ matrix.target }}/release/${BIN_NAME}${SUFFIX}"

          if [ -f "$ARTIFACT" ]; then
            cp "$ARTIFACT" "${BIN_NAME}-${{ matrix.artifact_suffix }}${SUFFIX}"
          else
            echo "Artifact not found: $ARTIFACT"
            exit 1
          fi

      # 7) Upload the artifact
      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: ${{ format('{0}-{1}{2}', 'RustWave', matrix.artifact_suffix, contains(matrix.target, 'windows') && '.exe' || '') }}
